[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.24.1"
serde ={version="1.0.167", features = ["derive"]}
serde_json = "1.0.100"
anyhow = "1.0.71"
structopt = { version = "0.3.26", default-features = false }
env_logger = "0.10.0"
log = "0.4.19"
